category: READING
defaultLocale: en
localizedSettings:
  developerEmail:
  developerName:
  displayName: Educational Smart Display App
  fullDescription:
  privacyPolicyUrl:
  pronunciation: Educational Smart Display App
  shortDescription:
  smallLogoImage:
  termsOfServiceUrl:
projectId: reading-dc6dd
usesInteractiveCanvas: true